import { describe, it, expect } from "vitest";
import { computeScaleBarRect, type ScaleBarLike } from "./scaleBarGeometry";
import backendCases from "./__fixtures__scaleBarBackendCases.json";

/* The fixture is generated by replaying the REAL backend placement maths from
   python-sidecar/figure_builder.py `_add_panel_scale_bars` (see the generator
   in the commit). If someone changes the Python formula without updating this
   port, these fail — which is exactly the drift that made the dragged bar land
   somewhere different from where it was dropped. */

interface Case {
  sb: ScaleBarLike;
  iw: number;
  ih: number;
  expect: { bx: number; by: number; barLen: number; barH: number; isBottom: boolean };
}

describe("scaleBarGeometry — parity with the Python backend", () => {
  it("matches the backend on every generated case", () => {
    const cases = backendCases as unknown as Case[];
    expect(cases.length).toBeGreaterThan(0);
    for (const c of cases) {
      const got = computeScaleBarRect(c.sb, c.iw, c.ih);
      const label = `${JSON.stringify(c.sb)} @ ${c.iw}x${c.ih}`;
      expect(got.bx, `bx ${label}`).toBeCloseTo(c.expect.bx, 6);
      expect(got.by, `by ${label}`).toBeCloseTo(c.expect.by, 6);
      expect(got.barLen, `barLen ${label}`).toBeCloseTo(c.expect.barLen, 6);
      expect(got.barH, `barH ${label}`).toBeCloseTo(c.expect.barH, 6);
      expect(got.isBottom, `isBottom ${label}`).toBe(c.expect.isBottom);
    }
  });
});

describe("scaleBarGeometry — behaviours the user reported", () => {
  const base: ScaleBarLike = {
    bar_length_microns: 100,
    micron_per_pixel: 1,
    bar_height: 6,
    edge_distance: 5,
    position_preset: "Custom",
    position_x: 50,
    position_y: 50,
  };

  it("label side NEVER moves the bar (the auto-flip annoyance)", () => {
    // Same bar, three label modes — bx/by must be byte-identical.
    const auto = computeScaleBarRect({ ...base, label_position: "auto" }, 1000, 1000);
    const above = computeScaleBarRect({ ...base, label_position: "above" }, 1000, 1000);
    const below = computeScaleBarRect({ ...base, label_position: "below" }, 1000, 1000);
    expect(above.bx).toBe(auto.bx);
    expect(above.by).toBe(auto.by);
    expect(below.bx).toBe(auto.bx);
    expect(below.by).toBe(auto.by);
    // ...even though the side genuinely differs.
    expect(above.isBottom).toBe(true);
    expect(below.isBottom).toBe(false);
  });

  it("dragging across the midline moves the bar smoothly, flipping only the label", () => {
    // Walk position_y across the 50% threshold; by must advance monotonically
    // with no jump, while isBottom flips exactly once.
    const ys = [46, 48, 49, 50, 51, 52, 54];
    const rects = ys.map((y) => computeScaleBarRect({ ...base, position_y: y }, 1000, 1000));
    for (let i = 1; i < rects.length; i++) {
      const step = rects[i].by - rects[i - 1].by;
      expect(step).toBeGreaterThan(0);              // always moves down
      expect(step).toBeLessThanOrEqual(20 + 1e-6);  // never jumps by a label height
    }
    const flips = rects.slice(1).filter((r, i) => r.isBottom !== rects[i].isBottom).length;
    expect(flips).toBe(1);
  });

  it("Custom: position_x is the bar's CENTRE, position_y its TOP", () => {
    const r = computeScaleBarRect({ ...base, position_x: 50, position_y: 40 }, 1000, 1000);
    expect(r.bx + r.barLen / 2).toBeCloseTo(500, 6);  // centre-x at 50%
    expect(r.by).toBeCloseTo(400, 6);                 // top at 40%
  });

  it("preset bar's centre is offset from its anchor (why the old hitbox missed)", () => {
    // Bottom-Right anchors the bar's RIGHT edge at (100-edge)%; its centre is
    // half a bar-length to the left — the old hitbox sat on the anchor.
    const r = computeScaleBarRect({ ...base, position_preset: "Bottom-Right" }, 1000, 1000);
    const anchorX = 950;
    expect(r.bx + r.barLen).toBeCloseTo(anchorX, 6);
    const centreX = r.bx + r.barLen / 2;
    expect(Math.abs(centreX - anchorX)).toBeGreaterThan(40); // demonstrably not the anchor
  });

  it("clamps a bar wider than the image instead of running off", () => {
    const r = computeScaleBarRect({ ...base, bar_length_microns: 5000 }, 1000, 1000);
    expect(r.bx).toBe(0);
  });
});
